packages:
  - "apps/*"
  - "configs/*"
  - "packages/**/*"

catalog:
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "prettier": "^3.4.1"
  "eslint": "^9.15.0"
  "typescript-eslint": "^8.15"
  "typescript": "^5.7.2"
  "postcss": "^8.4.49"
  "tsup": "^8.3.5"
  "vite": "^6.0.3"
  "vitest": "^2.1.8"
  "@vitejs/plugin-react": "^4.3.4"
  "@eslint/js": "^9.15.0"
  "@types/eslint": "^9.6.1"
  "@types/node": "^22.10.0"
  "@types/react": "^18.3.1"
  "@types/react-dom": "^18.3.1"
